version: '3'

services:
  mongo:
    image: mongo:4.0
    container_name: mongo
    ports:
      - '27017:27017'
    command: [--auth]

  workoutlog:
    container_name: workoutlog
    image: woochanlee/workoutlog:1.3.3
    ports:
      - '5000:5000'
    links:
      - 'mongo:mongo'
